[tool.poetry]
name = "tagbot-web"
version = "1.0.0"
description = "Web service for TagBot error reporting"
authors = ["Chris de Graaf <me@cdg.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "3.1.2"
PyGithub = "^2.7.0"
pylev = "^1.3.0"
MarkupSafe = "3.0.3"
itsdangerous = "2.2.0"
werkzeug = "3.1.4"

[tool.poetry.group.dev.dependencies]
boto3 = "^1.42.1"
pytest = "^8"
pytest-cov = "^7.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
