[tool.poetry]
name = "tagbot"
version = "1.19.4"
description = "Creates tags, releases, and changelogs for your Julia packages when they're registered"
authors = ["Chris de Graaf <me@cdg.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "3.0.3"
Jinja2 = "^3"
PyGithub = "^2.3.0"
click = "^8"
docker = "^7.1.0"
pexpect = "^4.8.0"
pylev = "^1.3.0"
python-gnupg = "^0.5.2"
pyyaml = "^6"
semver = "^3.0.2"
toml = "^0.10.0"
MarkupSafe = "2.1.5"
itsdangerous = "2.2.0"
werkzeug = "3.0.4"
types-requests = "^2.31.0"
types-toml = "^0.10.8"
types-PyYAML = "6.0.12.20240808"
setuptools = "^73.0.1"
wheel = "^0.44.0"

[tool.poetry.dev-dependencies]
black = "^24.3"
boto3 = "^1.35.19"
flake8 = "^7"
mypy = "^1.5"
pytest-cov = "^5.0.0"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
