[tool.poetry]
name = "tagbot"
version = "1.18.0"
description = "Creates tags, releases, and changelogs for your Julia packages when they're registered"
authors = ["Chris de Graaf <me@cdg.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2"
Jinja2 = "^3"
PyGithub = "1.58.2"
click = "^8"
docker = "^4.2.0"
pexpect = "^4.8.0"
pylev = "^1.3.0"
python-gnupg = "^0.4.7"
pyyaml = "^6"
semver = "^2.10.0"
toml = "^0.10.0"
MarkupSafe = "2.0.1"
itsdangerous = "2.0.1"
werkzeug = "2.0.3"

[tool.poetry.dev-dependencies]
black = "^23.11"
boto3 = "^1.13.8"
flake8 = "^3.8.1"
mypy = "^1.5"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
